### PR TITLE
Xenial pipeline

### PR DESCRIPTION
**Pull request by thelamer**
When this is merged the x86 variant will be replaced with a meta tag that will still function.

We will then be able to set the logic downstream on the other base images to use the arm images that will be available on this main repo.

Given the implications of merging this, test thoroughly locally. I have run it though basic loops on all three arches.

### CODE REVIEW

**Comment by aptalca** [comment]
Just to confirm, we'll disable the build jobs for x86 before pulling these in, but leave the arm ones active while we are migrating downstream images over, right?

Also, will these tag the `latest`?

**Comment by thelamer** [comment]
Exactly , and no they only tag the specific meta tag defined

**Comment by aptalca** [comment]
oh, good. I tested with a few images locally and didn't notice issues.

I don't think any of our downstream images use `latest` for the baseimage. I'll go ahead and merge unless there are other concerns

**Comment by thelamer** [comment]
As I say, this will only hit "live" stuff using x86 and the images are solid . I think the big decision still needs to be made by the team regarding armv7 but we can proceed with base image conversion and prs on repos while that decision is still pending

**Review by aptalca — APPROVED** [review]

**Pull request merged**
